@startuml
:用户:-->:学生:
:用户:-->:老师:
(查看学生列表)-->:用户:
:学生:-->(查看成绩)
:学生:-->(选择学期课程)
:老师:-->(评定成绩)
:老师:-->(选择学期课程 )
:老师:-->(查询学生成绩)
(修改密码)-->:用户:
(修改用户信息)-->:用户:
(查看用户信息)-->:用户:
(登入)-->:用户:
(登出)-->:用户:
@enduml