@startuml
title:学生列表顺序图
actor user
participant users
participant students
participant course
participant test
alt 用户如果是老师
user->users :登录
users->students :获取学生信息
students->course:获取课程信息
course->test:获取实验信息
test->users:返回学生的信息及课程信息，显示评定选项
users->user:登出
else 用户是学生
user->users :登录
users->students :获取学生信息
students->course:获取课程信息
course->test:获取实验信息
test->users:返回学生的信息及课程信息，显示查看个人分数选项
users->user:登出
else 游客
user->users :登录
users->students :获取学生信息
students->course:获取课程信息
course->test:获取实验信息
test->users:返回学生的信息及课程信息
users->user:登出
end

@enduml