@startuml
title:查看成绩顺序图
actor user
participant users
participant teacher
participant students

participant course
participant test
participant score
user->users:登入，判断登录身份
alt 老师
users->teacher:身份是老师
students->course:获取当前课程信息
course->test:获取选中课程的所有学生实验信息
test->score:获取当前实验各评分信息
score->teacher:返回当前课程所有学生实验信息和评分信息
teacher->users:退出
end
alt 学生
users->students:身份是学生
students->course:获取当前学生选中课程信息
course->test:获取选中课程的实验信息
test->score:获取当前实验各评分信息
score->students:返回本人当前课程实验信息和评分信息
students->users:退出
end

users->user:退出
@enduml