@startuml
title:评定成绩图
actor user
participant users
participant teacher
participant student
participant course
participant courseteach
participant coursestu
alt 老师
user->users:登录
users->teacher:获取老师信息
teacher->course:获取选中学期所有课程
course->courseteach:选择课程保存
courseteach->teacher:返回所选课程
teacher->user:退出
 else 学生
user->users:登录
users->student:获取学生信息
student->course:获取选中学期所有课程
course->coursestu:选择课程保存
coursestu->student:返回所选课程
student->user:退出

end
@enduml