@startuml
馆藏目录"1"-"1...*"馆藏资源品种
馆藏资源品种"1"-"*"预定记录
馆藏资源品种"1"*-"*"资源项:拥有
馆藏资源品种<|--碟片品种
馆藏资源品种<|--图书品种
资源项"1"--"0..1"借书记录
借书记录"*"--"1"图书管理员:登记
借书记录"1"--"0..1"逾期记录
借书记录-读者
预定记录"*"--"1"读者
逾期记录"*"-"0..1"罚款细则:使用

class 馆藏资源品种{
   资源名称
   国际出版号
   价格
   简介
   馆藏数量
   可借数量
}

class 碟片品种{
   碟片类型
   碟片数
   制作公司
}

class 图书品种{
   作者
   出版社
   出版日期
}

class 预定记录{
   预定日期
}

class 资源项{
   馆藏流水号
   状态
}

class 借书记录{
   借书日期
   归还日期
}

class 读者{
   姓名
   身份证号
   借书卡号
   图书限额
   已借图书数
   碟片限额
   已借图书数

}

class 图书管理员{
   职工号
   姓名
}

class 逾期记录{
   逾期天数
}
@enduml