@startuml
left to right direction
skinparam packageStyle rectangle
actor 读者
actor 管理员
rectangle 图书借阅 {
   管理员-->(借出图书)
   管理员-->(归还图书)
   管理员-->(还书超时登记罚款)
   管理员-->(维护书目)
   管理员-->(维护读者信息)
   管理员 --> (查询书目)
  (查询书目) <--读者
  (查询借阅情况) <--读者
  (预定图书) <--读者
  (取消预订) <--读者

}
newpage
left to right direction
actor 管理员
actor 出版社
rectangle 图书购买 {

  管理员-->(订购图书)
  管理员-->(查阅数目)
  管理员-->(取消预订)
  管理员-->(退换图书)
  (接收订单) <--出版社
  (派发图书) <--出版社
  (退换图书) <--出版社


}
@enduml